// This file is auto-generated by update-p5-types.js.
// It provides global-mode declarations for p5.sound addon functions
// that exist in the bundled runtime p5.sound.min.js.

import p5 = require('./p5');

declare global {
  function getAudioContext(): object;
  function loadSound(path: string | any[], successCallback?: (...args: any[]) => any, errorCallback?: (...args: any[]) => any, whileLoading?: (...args: any[]) => any): p5.SoundFile | Promise<p5.SoundFile>;
  function setAudioContext(audioContext: AudioContext): void;
  function userStartAudio(elements?: Element | any[], callback?: (...args: any[])=> any): Promise<any>;
  function userStopAudio(): Promise<void>;
}

export {};
